Major: docker compiler-explorer: use frozen tag to avoid npm compile error
npm compile error on latest tag gh-6747:
    compiler-explorer  | ERROR in ./static/panes/editor.ts 1213:45-60
    compiler-explorer  | [tsl] ERROR in /compiler-explorer/static/panes/editor.ts(1213,46)
    compiler-explorer  |       TS2339: Property 'autoCloseQuotes' does not exist on type 'SiteSettings'.

use tag gh-6329 to avoid npm compile error