Minor: update README for Ubuntu 22.04
1. add libstdc++-12-dev for solving 'clang++' compilation error with "fatal error: 'iostream' file not found"
2. add libgtest-dev for solving 'cmake' build error with "Could NOT find GTest" (Reference: https://stackoverflow.com/questions/24295876/cmake-cannot-find-googletest-required-library-in-ubuntu)
3. and other some packages for Ubuntu 22.04
4. dropped Ubuntu 20.04 support